const questionIndex = 0;
const lowerIndex = 1;
const upperIndex = 2;

const questions = [
    // Format: [Question, Starting date, End date]
    ["Is Canada it's own country?", 1867, ""],
    ["Is Panama independent from Colombia?", 1903, ""],
    ["Is there a railway linking Moscow and Vladivostok?", 1904, ""],
    ["Is Norway independent from Sweden?", 1905, ""],
    ["Has Japan annexed Korea?", 1910, 1945],
    ["Is the Republic of China present in the Chinese mainland?", 1912, 1949],
    ["Is Yugoslavia present?", 1918, 1992],
    ["Is the Austro-Hungarian Empire present?", "", 1918],
    ["Is the Soviet Union present?", 1922, 1991],
    ["Is the Republic of Turkey present?", 1923, ""],
    ["Has Constantinople become Istanbul?", 1930, ""],
    ["Is Saudi Arabia present?", 1932, ""],
    ["Has Persia become Iran?", 1935, ""],
    ["Is Indonesia independent from the Netherlands?", 1945, ""],
    ["Has Königsberg become Kaliningrad?", 1946, ""],
    ["Is India and Pakistan separate?", 1947, ""],
    ["Is Isreal present?", 1948, ],
    ["Is Taiwan present?", 1949, ""],
    ["Is China called the People's Republic of China?", 1949, ""],
    ["Has Gyeongseong become Seoul (South Korea)?", 1950, ""],
    ["Is United Arab Republic present?", 1958, 1961],
    ["Is any of these contries present? Cameroon, Togo, Mali Federation, Madagascar, Dahomey, Niger, Upper Volta, Ivory Coast, Chad, Central African Republic, Republic of the Congo, Gabon, Mauritania", 1960, ""],
    ["Is Tanzania present?", 1961, ""],
    ["Is Algeria present?", 1962, ""],
    ["Is Malawi and Zambia present?", 1964, ],
    ["Has Nyasaland become Malawi?", 1964, ""],
    ["Has Leopoldville become Kinshasa (Democratic Republic of the Congo)?", 1964, ""],
    ["Is Malta independent from Great Britain?", 1964, ""],
    ["Has Bechuanaland become Botswana?", 1966, ""],
    ["Has East Pakistan become Bangladash?", 1971, ""],
    ["Is United Arab Emirates present?", 1971, ],
    ["Has West Germany recognized the Oder-Neisse Border? (Poland looks like today)?", 1971, ],
    ["Is Cyprus divided?", 1974, ""],
    ["Has Dahomey become Benin?", 1975, ""],
    ["Has Lourenço Marques become Maputo (Mozambique)?", 1976, ""],
    ["Has Salisbury become Harare (Zimbabwe)", 1976, ""],
    ["Has Rhodesia become Zimbabwe?", 1980, ""],
    ["Has Upper Volta become Burkina Faso?", 1984, ""],
    ["Is Germany united?", 1989, ""],
    ["Has Burma become Myanmar?", 1989, ""],
    ["Is Namibia independent from south Africa?", 1990, ""],
    ["Has Leningrad become Saint Petersburg (Russia)?", 1991, ""],
    ["Has Alma-Ata become Almaty (Kazakhstan)?", 1991, ""],
    ["Is Czechoslovakia Present?", "", 1993],
    ["Is Eritrea independent from Ethiopia?", 1993, ""],
    ["Has Bombay become Mumbai (India)?", 1995, ""],
    ["Has Madras become Chennai (India)?", 1996, ""],
    ["Has Zaire become Democratic Republic of the Congo?", 1997, ""],
    ["Has Kampuchea become Cambodia?", 1997, ""],
    ["Has Peking become Beijing (China)?", 1997, ""],
    ["Has Calcutta become Kolkata (India)?", 2001, ""],
    ["Has the Federal Republic of Yugoslavia become Serbia and Montenegro?", 2003, ""],
    ["Is Montenegro and Serbia separate countries?", 2006, ""],
    ["Is Kosovo present?", 2008, ""],
    ["Is South Sudan present?", 2011, ""],
    ["Has Swaziland become Eswatini?", 2018, ""],
    ["Has Macedonia become North Macedonia?", 2019, ""],
    ["Is Astana called Nur-Sultan?", 2019, 2022],

    // ["", , ],
];